import OpenAI from "openai";
import { jsPDF } from "jspdf";

// Hard cap on the number of characters we send to the model. ~30k chars is
// well within gpt-4o-mini's context window and keeps the cost predictable
// even when a user uploads a 200-page PDF.
const MAX_CHARS_FOR_SUMMARY = 30_000;

export type SummaryResult = {
  text: string;
  pdfBytes: Uint8Array;
};

/**
 * Asks OpenAI to summarise a file and returns both the markdown summary and
 * a rendered PDF. Throws if either step fails — the caller decides whether
 * to surface the error or fall back silently.
 */
export async function summariseFile(args: {
  text: string;
  filename: string;
  language?: string;
}): Promise<SummaryResult> {
  const text = await callOpenAI({
    text: args.text.slice(0, MAX_CHARS_FOR_SUMMARY),
    filename: args.filename,
    language: args.language,
  });

  const pdfBytes = renderPdf(text, args.filename);
  return { text, pdfBytes };
}

async function callOpenAI(args: {
  text: string;
  filename: string;
  language?: string;
}): Promise<string> {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) throw new Error("OPENAI_API_KEY is not set");

  const client = new OpenAI({ apiKey });
  const model = process.env.OPENAI_MODEL || "gpt-4o-mini";

  const language = args.language && args.language.length > 0 ? args.language : "English";

  const completion = await client.chat.completions.create({
    model,
    temperature: 0.3,
    messages: [
      {
        role: "system",
        content: [
          "You are a concise study assistant that summarises documents for medical and paramedical students.",
          "Produce a clean, exam-ready summary that's faithful to the source — never invent facts.",
          "Use plain text with simple section headings; avoid markdown tables.",
          "If the document covers a clinical topic, include high-yield clinical points the reader is likely to be tested on.",
          `Output language: ${language}.`,
        ].join(" "),
      },
      {
        role: "user",
        content: [
          `File name: ${args.filename}`,
          "",
          "Write a study summary of the following document with this structure:",
          "  • A 2–4 sentence overview at the top.",
          "  • Section headings (Key concepts, Important definitions, Clinical/practical points, etc.) with bulleted items underneath.",
          "  • A short \"Highlights\" list of 5–10 single-sentence takeaways at the end.",
          "Aim for ~600–1200 words depending on document length. Keep bullets short.",
          "",
          "--- Document content ---",
          args.text,
        ].join("\n"),
      },
    ],
  });

  const out = completion.choices[0]?.message?.content?.trim();
  if (!out) throw new Error("Empty summary from OpenAI");
  return out;
}

function renderPdf(text: string, filename: string): Uint8Array {
  const doc = new jsPDF({ unit: "pt", format: "a4" });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 56;
  const maxWidth = pageWidth - margin * 2;

  let y = margin;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  const titleLines = doc.splitTextToSize(`Summary — ${filename}`, maxWidth);
  doc.text(titleLines, margin, y);
  y += titleLines.length * 20 + 6;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(120);
  doc.text(`Generated by MedExam Hub · ${new Date().toLocaleDateString()}`, margin, y);
  y += 18;
  doc.setTextColor(0);

  doc.setDrawColor(220);
  doc.line(margin, y, pageWidth - margin, y);
  y += 14;

  // Body — render line by line, switching font weight when a line looks like a heading.
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trimEnd();
    if (line.length === 0) {
      y += 6;
      continue;
    }
    const isHeading = /^(#+\s+|\*\*.*\*\*$)/.test(line) || /^[A-Z][A-Za-z0-9 /&\-]{2,40}:?$/.test(line.trim());
    const cleaned = line
      .replace(/^#+\s+/, "")
      .replace(/^\*\*/, "")
      .replace(/\*\*$/, "");

    doc.setFont("helvetica", isHeading ? "bold" : "normal");
    doc.setFontSize(isHeading ? 12 : 11);

    const wrapped = doc.splitTextToSize(cleaned, maxWidth);
    const lineHeight = isHeading ? 16 : 14;
    for (const w of wrapped) {
      if (y + lineHeight > pageHeight - margin) {
        doc.addPage();
        y = margin;
      }
      doc.text(w, margin, y);
      y += lineHeight;
    }
    if (isHeading) y += 4;
  }

  // jsPDF returns ArrayBuffer with output("arraybuffer"); wrap as Uint8Array.
  const buf = doc.output("arraybuffer") as ArrayBuffer;
  return new Uint8Array(buf);
}
