import { prisma } from "@/lib/db";
import { PLAN_LIMITS, currentYearMonth, effectiveMonthlyQuestions } from "@/lib/plans";
import { drainBonus, getBonusBalance } from "@/lib/credits";
import type { Plan } from "@/generated/prisma/client";

// Quota is tracked in QUESTIONS, not exams. Each question generated by the AI
// deducts 1 from the user's monthly question budget — billed at generation time
// regardless of whether the user finishes the exam.
const KIND = "questions_used";

export type QuotaStatus = {
  used: number;       // total used this month (from plan + bonus combined)
  limit: number;      // plan monthly + bonus pool — what `remaining` is computed against
  remaining: number;  // limit - used (or just bonus balance if plan exhausted)
  bonus: number;      // perpetual bonus pool size at time of read
  planLimit: number;  // plan's monthly cap (excluding bonus)
};

export async function getMonthlyQuestionsUsage(
  userId: string,
  plan: Plan
): Promise<QuotaStatus> {
  const ym = currentYearMonth();

  const [agg, bonus] = await Promise.all([
    prisma.usageLog.aggregate({
      where: { userId, kind: KIND, yearMonth: ym },
      _sum: { count: true },
    }),
    getBonusBalance(userId, "questions"),
  ]);
  const used = agg._sum.count ?? 0;
  // Use the effective limit (honours the time-windowed FREE boost) rather
  // than the static PLAN_LIMITS value. Outside the boost window this is
  // identical to PLAN_LIMITS[plan].monthlyQuestions.
  const planLimit = effectiveMonthlyQuestions(plan);

  // Combined ceiling = plan monthly + perpetual bonus pool. The bonus pool
  // only actually drains once monthly usage exceeds planLimit (handled in
  // recordQuestionsUsed), so the user sees their bonus balance carrying
  // across months until they actually need it.
  const limit = planLimit + bonus;
  const remaining = Math.max(0, limit - used);

  return { used, limit, remaining, bonus, planLimit };
}

export async function recordQuestionsUsed(userId: string, count: number): Promise<void> {
  if (count <= 0) return;
  const ym = currentYearMonth();

  // What was used before this batch? Needed to know if (and how much of)
  // this batch overflows into bonus.
  const agg = await prisma.usageLog.aggregate({
    where: { userId, kind: KIND, yearMonth: ym },
    _sum: { count: true },
  });
  const usedBefore = agg._sum.count ?? 0;

  await prisma.usageLog.create({
    data: { userId, kind: KIND, count, yearMonth: ym },
  });

  // If we crossed the plan limit with this batch, drain the overflow from
  // the bonus pool. We need the user's plan to know the limit.
  const user = await prisma.user.findUnique({
    where: { id: userId },
    select: { plan: true },
  });
  if (!user) return;
  // Mirror the effective limit used in getMonthlyQuestionsUsage so the
  // overflow-into-bonus math agrees with what the user was told they had.
  const planLimit = effectiveMonthlyQuestions(user.plan);
  const usedAfter = usedBefore + count;
  const overflowBefore = Math.max(0, usedBefore - planLimit);
  const overflowAfter = Math.max(0, usedAfter - planLimit);
  const bonusToDrain = overflowAfter - overflowBefore;

  if (bonusToDrain > 0) {
    await drainBonus(userId, "questions", bonusToDrain);
  }
}

export const getMonthlyExamUsage = getMonthlyQuestionsUsage;

// File-upload quota tracking. We use the FileUpload.yearMonth column directly
// instead of a UsageLog row so we can also display the user's recent uploads.
export async function getMonthlyFileUploads(userId: string, plan: Plan): Promise<QuotaStatus> {
  const ym = currentYearMonth();
  const [used, bonus] = await Promise.all([
    prisma.fileUpload.count({ where: { userId, yearMonth: ym } }),
    getBonusBalance(userId, "files"),
  ]);
  const planLimit = PLAN_LIMITS[plan].fileUploadsPerMonth;
  const limit = planLimit + bonus;
  return { used, limit, remaining: Math.max(0, limit - used), bonus, planLimit };
}

/**
 * Call after a successful FileUpload row is created. If the user's monthly
 * upload count just exceeded their plan limit, drain 1 from their bonus
 * file pool. Idempotent on its own — callers should call once per upload.
 */
export async function recordFileUploaded(userId: string, plan: Plan): Promise<void> {
  const ym = currentYearMonth();
  const used = await prisma.fileUpload.count({ where: { userId, yearMonth: ym } });
  const planLimit = PLAN_LIMITS[plan].fileUploadsPerMonth;
  if (used > planLimit) {
    // We can only drain 1 here because each upload is a single unit.
    await drainBonus(userId, "files", 1);
  }
}
