import { prisma } from "@/lib/db";
import { PLAN_LIMITS, currentYearMonth } from "@/lib/plans";
import type { Plan } from "@/generated/prisma/client";

// Quota is tracked in QUESTIONS, not exams. Each question generated by the AI
// deducts 1 from the user's monthly question budget — billed at generation time
// regardless of whether the user finishes the exam.
const KIND = "questions_used";

export type QuotaStatus = {
  used: number;
  limit: number;
  remaining: number;
  bonus?: number;
};

async function sumActiveBonus(userId: string, kind: "questions" | "files"): Promise<number> {
  const ym = currentYearMonth();
  const agg = await prisma.bonusGrant.aggregate({
    where: { userId, kind, yearMonth: ym },
    _sum: { amount: true },
  });
  return agg._sum.amount ?? 0;
}

export async function getMonthlyQuestionsUsage(
  userId: string,
  plan: Plan
): Promise<QuotaStatus> {
  const ym = currentYearMonth();

  const [agg, bonus] = await Promise.all([
    prisma.usageLog.aggregate({
      where: { userId, kind: KIND, yearMonth: ym },
      _sum: { count: true },
    }),
    sumActiveBonus(userId, "questions"),
  ]);
  const used = agg._sum.count ?? 0;
  const limit = PLAN_LIMITS[plan].monthlyQuestions + bonus;

  return { used, limit, remaining: Math.max(0, limit - used), bonus };
}

export async function recordQuestionsUsed(userId: string, count: number): Promise<void> {
  if (count <= 0) return;
  await prisma.usageLog.create({
    data: {
      userId,
      kind: KIND,
      count,
      yearMonth: currentYearMonth(),
    },
  });
}

// Re-exported with the legacy name so older imports still resolve while we
// finish migrating call sites.
export const getMonthlyExamUsage = getMonthlyQuestionsUsage;

// File-upload quota tracking. We use the FileUpload.yearMonth column directly
// instead of a UsageLog row so we can also display the user's recent uploads.
export async function getMonthlyFileUploads(userId: string, plan: Plan): Promise<QuotaStatus> {
  const ym = currentYearMonth();
  const [used, bonus] = await Promise.all([
    prisma.fileUpload.count({ where: { userId, yearMonth: ym } }),
    sumActiveBonus(userId, "files"),
  ]);
  const limit = PLAN_LIMITS[plan].fileUploadsPerMonth + bonus;
  return { used, limit, remaining: Math.max(0, limit - used), bonus };
}
