import {
  AlignmentType,
  Document,
  HeadingLevel,
  ImageRun,
  Packer,
  PageBreak,
  Paragraph,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
} from "docx";
import { renderPrismaTextSummary, safeParsePrismaFlow } from "@/lib/prisma-flow";
import { svgToPng } from "@/lib/stats-charts";
import { fmt, fmtP } from "@/lib/stats-engine";
import type {
  AnovaResult,
  BoxplotResult,
  ChiSquareResult,
  CorrelationCell,
  DescriptiveRow,
  GroupMeansRow,
  HistogramBins,
  KaplanMeierResult,
  KruskalWallisResult,
  LinearRegressionResult,
  LogisticRegressionResult,
  MannWhitneyResult,
  NormalityResult,
  PairedTResult,
  RocResult,
  ScatterResult,
  TTestResult,
  WilcoxonResult,
} from "@/lib/stats-engine";

export type AnalysisExport = {
  id: string;
  kind: string;
  title: string;
  resultJson: string | null;
  resultSvg: string | null;
};

export type ResearchExport = {
  title: string;
  kindLabel: string;
  authorName: string | null;
  university: string | null;
  specialty: string | null;
  studyType: string | null;
  language: string;
  citationStyle: string;
  sections: Array<{ title: string; content: string; metadataJson?: string | null }>;
  analyses?: AnalysisExport[];
};

export async function renderResearchDocx(p: ResearchExport): Promise<Buffer> {
  const cover: Paragraph[] = [
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 1800, after: 400 },
      children: [
        new TextRun({
          text: p.kindLabel.toUpperCase(),
          bold: true,
          size: 22,
          color: "555555",
        }),
      ],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 200, after: 600 },
      children: [new TextRun({ text: p.title, bold: true, size: 44 })],
    }),
    p.authorName
      ? new Paragraph({
          alignment: AlignmentType.CENTER,
          spacing: { before: 400, after: 200 },
          children: [new TextRun({ text: p.authorName, size: 26 })],
        })
      : new Paragraph({}),
    p.university
      ? new Paragraph({
          alignment: AlignmentType.CENTER,
          spacing: { after: 100 },
          children: [new TextRun({ text: p.university, italics: true, size: 22 })],
        })
      : new Paragraph({}),
    p.specialty || p.studyType
      ? new Paragraph({
          alignment: AlignmentType.CENTER,
          spacing: { after: 100 },
          children: [
            new TextRun({
              text: [p.specialty, p.studyType].filter(Boolean).join(" · "),
              size: 22,
              color: "666666",
            }),
          ],
        })
      : new Paragraph({}),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 1200, after: 600 },
      children: [
        new TextRun({
          text: `Generated by MedExam Hub — Research Assistant · ${new Date().toLocaleDateString()}`,
          italics: true,
          size: 18,
          color: "888888",
        }),
      ],
    }),
    new Paragraph({ children: [new PageBreak()] }),
  ];

  const body: Paragraph[] = [];
  for (const section of p.sections) {
    body.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 400, after: 200 },
        children: [new TextRun({ text: section.title, bold: true, size: 32 })],
      })
    );

    const prismaData = section.metadataJson
      ? safeParsePrismaFlow(section.metadataJson)
      : null;
    const effectiveText = prismaData
      ? renderPrismaTextSummary(prismaData) +
        "\n\n[A visual PRISMA flow diagram is shown in the on-screen editor — paste a screenshot here.]"
      : section.content;

    for (const line of effectiveText.split(/\r?\n/)) {
      const trimmed = line.trim();
      if (trimmed.length === 0) {
        body.push(new Paragraph({}));
        continue;
      }
      const bulletMatch = /^[-•*]\s+(.*)/.exec(trimmed);
      const numberedMatch = /^\d+[.)]\s+(.*)/.exec(trimmed);
      if (bulletMatch) {
        body.push(
          new Paragraph({
            bullet: { level: 0 },
            spacing: { after: 100 },
            children: [new TextRun({ text: bulletMatch[1], size: 22 })],
          })
        );
        continue;
      }
      if (numberedMatch) {
        body.push(
          new Paragraph({
            numbering: { reference: "default-numbered", level: 0 },
            spacing: { after: 100 },
            children: [new TextRun({ text: numberedMatch[1], size: 22 })],
          })
        );
        continue;
      }
      if (trimmed.length < 80 && trimmed.endsWith(":")) {
        body.push(
          new Paragraph({
            spacing: { before: 200, after: 100 },
            children: [
              new TextRun({ text: trimmed.replace(/:$/, ""), bold: true, size: 24 }),
            ],
          })
        );
        continue;
      }
      body.push(
        new Paragraph({
          spacing: { after: 140 },
          children: [new TextRun({ text: trimmed, size: 22 })],
        })
      );
    }
  }

  const analysisChildren: (Paragraph | Table)[] = [];
  const populated = (p.analyses ?? []).filter((a) => a.resultJson);
  if (populated.length > 0) {
    analysisChildren.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 600, after: 200 },
        children: [
          new TextRun({ text: "Statistical Analysis Appendix", bold: true, size: 32 }),
        ],
      })
    );
    for (const a of populated) {
      analysisChildren.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 320, after: 140 },
          children: [new TextRun({ text: a.title, bold: true, size: 26 })],
        })
      );
      const blocks = await analysisBlocksForDocx(a);
      for (const b of blocks) analysisChildren.push(b);
    }
  }

  const doc = new Document({
    creator: p.authorName ?? "MedExam Hub",
    title: p.title,
    description: p.kindLabel,
    numbering: {
      config: [
        {
          reference: "default-numbered",
          levels: [
            {
              level: 0,
              format: "decimal",
              text: "%1.",
              alignment: AlignmentType.LEFT,
            },
          ],
        },
      ],
    },
    sections: [
      {
        properties: {},
        children: [...cover, ...body, ...analysisChildren],
      },
    ],
  });

  return Buffer.from(await Packer.toBuffer(doc));
}

// ─────────────────────────────────────────────────────────────────────────────
// Analysis → DOCX block(s).
// ─────────────────────────────────────────────────────────────────────────────

async function analysisBlocksForDocx(a: AnalysisExport): Promise<(Paragraph | Table)[]> {
  const out: (Paragraph | Table)[] = [];
  let parsed: unknown = null;
  try {
    parsed = a.resultJson ? JSON.parse(a.resultJson) : null;
  } catch {
    parsed = null;
  }
  if (!parsed) {
    out.push(textPara("(No computed result.)"));
    return out;
  }

  const appendChart = async () => {
    if (a.resultSvg) {
      const png = await rasteriseChart(a.resultSvg);
      if (png) out.push(imageParagraph(png));
    }
  };

  switch (a.kind) {
    case "descriptives":
      out.push(descriptivesTable(parsed as DescriptiveRow[]));
      break;
    case "compare_means": {
      const r = parsed as { tTest: TTestResult; groupMeans: GroupMeansRow[] };
      out.push(groupMeansTable(r.groupMeans));
      out.push(...tTestBlock(r.tTest));
      await appendChart();
      break;
    }
    case "paired_t":
      out.push(...pairedTBlock(parsed as PairedTResult));
      break;
    case "mann_whitney": {
      const r = parsed as { mannWhitney: MannWhitneyResult; groupMeans: GroupMeansRow[] };
      out.push(groupMeansTable(r.groupMeans));
      out.push(...mannWhitneyBlock(r.mannWhitney));
      await appendChart();
      break;
    }
    case "wilcoxon":
      out.push(...wilcoxonBlock(parsed as WilcoxonResult));
      break;
    case "anova": {
      const r = parsed as { anova: AnovaResult; groupMeans: GroupMeansRow[] };
      out.push(groupMeansTable(r.groupMeans));
      out.push(anovaTable(r.anova));
      out.push(...anovaSummary(r.anova));
      await appendChart();
      break;
    }
    case "kruskal_wallis": {
      const r = parsed as { kruskalWallis: KruskalWallisResult; groupMeans: GroupMeansRow[] };
      out.push(groupMeansTable(r.groupMeans));
      out.push(...kruskalBlock(r.kruskalWallis));
      await appendChart();
      break;
    }
    case "chi_square":
      out.push(...chiSquareBlock(parsed as ChiSquareResult));
      break;
    case "correlation":
      out.push(
        correlationTable(parsed as { columns: string[]; cells: CorrelationCell[] })
      );
      break;
    case "linear_regression": {
      const lr = parsed as LinearRegressionResult;
      out.push(...linearRegBlock(lr));
      await appendChart();
      break;
    }
    case "logistic_regression": {
      const lr = parsed as LogisticRegressionResult;
      out.push(...logisticBlock(lr));
      await appendChart();
      break;
    }
    case "kaplan_meier": {
      const km = parsed as KaplanMeierResult;
      out.push(...kaplanMeierBlock(km));
      await appendChart();
      break;
    }
    case "roc": {
      const r = parsed as RocResult;
      out.push(...rocBlock(r));
      await appendChart();
      break;
    }
    case "normality":
      out.push(...normalityBlock(parsed as NormalityResult));
      break;
    case "histogram": {
      const h = parsed as HistogramBins;
      out.push(
        textPara(
          `n = ${h.n} · mean = ${fmt(h.mean)} · range [${fmt(h.min)}, ${fmt(h.max)}]`
        )
      );
      await appendChart();
      break;
    }
    case "boxplot": {
      const b = parsed as BoxplotResult;
      out.push(boxplotTable(b));
      await appendChart();
      break;
    }
    case "scatter": {
      const s = parsed as ScatterResult;
      out.push(
        textPara(
          `n = ${s.n} · r = ${fmt(s.r, 3)} · R² = ${fmt(s.r2, 3)} · slope = ${fmt(
            s.slope,
            3
          )} · intercept = ${fmt(s.intercept, 3)}`
        )
      );
      await appendChart();
      break;
    }
    default:
      out.push(textPara(`(Unknown analysis kind: ${a.kind})`));
  }
  return out;
}

async function rasteriseChart(svg: string): Promise<Buffer | null> {
  try {
    return await svgToPng(svg, 900);
  } catch {
    return null;
  }
}

function imageParagraph(png: Buffer): Paragraph {
  return new Paragraph({
    spacing: { before: 160, after: 200 },
    children: [
      new ImageRun({
        type: "png",
        data: new Uint8Array(png),
        transformation: { width: 540, height: 300 },
      }),
    ],
  });
}

function textPara(text: string, opts?: { bold?: boolean }): Paragraph {
  return new Paragraph({
    spacing: { after: 140 },
    children: [new TextRun({ text, size: 22, bold: opts?.bold })],
  });
}

function headerCell(text: string): TableCell {
  return new TableCell({
    children: [
      new Paragraph({ children: [new TextRun({ text, bold: true, size: 20 })] }),
    ],
  });
}

function bodyCell(text: string, opts?: { mono?: boolean }): TableCell {
  return new TableCell({
    children: [
      new Paragraph({
        children: [
          new TextRun({
            text,
            size: 20,
            font: opts?.mono ? "Courier New" : undefined,
          }),
        ],
      }),
    ],
  });
}

function descriptivesTable(rows: DescriptiveRow[]): Table {
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      new TableRow({
        children: ["Variable", "n", "Mean", "Median", "SD", "Min", "Max", "Q1", "Q3"].map(
          headerCell
        ),
      }),
      ...rows.map(
        (r) =>
          new TableRow({
            children: [
              bodyCell(r.column),
              bodyCell(String(r.n), { mono: true }),
              bodyCell(fmt(r.mean), { mono: true }),
              bodyCell(fmt(r.median), { mono: true }),
              bodyCell(fmt(r.sd), { mono: true }),
              bodyCell(fmt(r.min), { mono: true }),
              bodyCell(fmt(r.max), { mono: true }),
              bodyCell(fmt(r.q1), { mono: true }),
              bodyCell(fmt(r.q3), { mono: true }),
            ],
          })
      ),
    ],
  });
}

function groupMeansTable(rows: GroupMeansRow[]): Table {
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      new TableRow({ children: ["Group", "n", "Mean", "SD"].map(headerCell) }),
      ...rows.map(
        (r) =>
          new TableRow({
            children: [
              bodyCell(r.group),
              bodyCell(String(r.n), { mono: true }),
              bodyCell(fmt(r.mean), { mono: true }),
              bodyCell(fmt(r.sd), { mono: true }),
            ],
          })
      ),
    ],
  });
}

function tTestBlock(t: TTestResult): Paragraph[] {
  return [
    textPara(
      `Welch's t-test: t = ${fmt(t.t, 3)}, df = ${fmt(t.df, 1)}, mean diff = ${fmt(
        t.meanDifference
      )}, p = ${fmtP(t.pValue)}`,
      { bold: true }
    ),
  ];
}

function pairedTBlock(t: PairedTResult): Paragraph[] {
  return [
    textPara(`Paired t-test: ${t.col1} vs ${t.col2} (n = ${t.n})`),
    textPara(
      `mean diff = ${fmt(t.meanDiff)}, SD = ${fmt(t.sdDiff)}, t = ${fmt(t.t, 3)}, df = ${t.df}, p = ${fmtP(t.pValue)}`,
      { bold: true }
    ),
  ];
}

function mannWhitneyBlock(mw: MannWhitneyResult): Paragraph[] {
  return [
    textPara(
      `Mann–Whitney U: U = ${fmt(mw.u, 1)}, Z = ${fmt(mw.z, 3)}, p = ${fmtP(mw.pValue)}`,
      { bold: true }
    ),
    textPara(
      `${mw.group1.name}: mean rank ${fmt(mw.group1.meanRank, 2)} (n=${mw.group1.n}); ${mw.group2.name}: mean rank ${fmt(mw.group2.meanRank, 2)} (n=${mw.group2.n})`
    ),
  ];
}

function wilcoxonBlock(w: WilcoxonResult): Paragraph[] {
  return [
    textPara(`Wilcoxon signed-rank: ${w.col1} vs ${w.col2} (n = ${w.n} non-zero diffs)`),
    textPara(
      `W+ = ${fmt(w.wPositive, 1)}, W− = ${fmt(w.wNegative, 1)}, Z = ${fmt(w.z, 3)}, p = ${fmtP(w.pValue)}`,
      { bold: true }
    ),
  ];
}

function anovaTable(a: AnovaResult): Table {
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      new TableRow({
        children: ["Source", "SS", "df", "MS", "F"].map(headerCell),
      }),
      new TableRow({
        children: [
          bodyCell("Between"),
          bodyCell(fmt(a.ssBetween), { mono: true }),
          bodyCell(String(a.dfBetween), { mono: true }),
          bodyCell(fmt(a.msBetween), { mono: true }),
          bodyCell(fmt(a.f, 3), { mono: true }),
        ],
      }),
      new TableRow({
        children: [
          bodyCell("Within"),
          bodyCell(fmt(a.ssWithin), { mono: true }),
          bodyCell(String(a.dfWithin), { mono: true }),
          bodyCell(fmt(a.msWithin), { mono: true }),
          bodyCell("—", { mono: true }),
        ],
      }),
    ],
  });
}

function anovaSummary(a: AnovaResult): Paragraph[] {
  return [
    textPara(
      `One-way ANOVA: F(${a.dfBetween}, ${a.dfWithin}) = ${fmt(a.f, 3)}, p = ${fmtP(a.pValue)}`,
      { bold: true }
    ),
  ];
}

function kruskalBlock(k: KruskalWallisResult): Paragraph[] {
  return [
    textPara(
      `Kruskal–Wallis: H = ${fmt(k.h, 3)}, df = ${k.df}, p = ${fmtP(k.pValue)}`,
      { bold: true }
    ),
  ];
}

function chiSquareBlock(c: ChiSquareResult): (Paragraph | Table)[] {
  const rows: TableRow[] = [
    new TableRow({
      children: ["", ...c.colLevels].map(headerCell),
    }),
    ...c.rowLevels.map(
      (rl, i) =>
        new TableRow({
          children: [
            bodyCell(rl),
            ...c.colLevels.map((_, j) =>
              bodyCell(`${c.observed[i][j]} (${fmt(c.expected[i][j], 1)})`, {
                mono: true,
              })
            ),
          ],
        })
    ),
  ];
  const out: (Paragraph | Table)[] = [
    textPara(`Cross-tabulation of ${c.rowVar} × ${c.colVar} (observed (expected)):`),
    new Table({ width: { size: 100, type: WidthType.PERCENTAGE }, rows }),
    textPara(
      `χ² = ${fmt(c.chi2, 3)}, df = ${c.df}, p = ${fmtP(c.pValue)}${
        typeof c.fisherP === "number" ? `; Fisher's exact p = ${fmtP(c.fisherP)}` : ""
      }`,
      { bold: true }
    ),
  ];
  if (c.warning) out.push(textPara(c.warning));
  return out;
}

function correlationTable(matrix: { columns: string[]; cells: CorrelationCell[] }): Table {
  const lookup = (rowCol: string, colCol: string) =>
    matrix.cells.find((c) => c.rowColumn === rowCol && c.colColumn === colCol);
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      new TableRow({ children: ["", ...matrix.columns].map(headerCell) }),
      ...matrix.columns.map(
        (rowCol) =>
          new TableRow({
            children: [
              bodyCell(rowCol),
              ...matrix.columns.map((colCol) => {
                const c = lookup(rowCol, colCol);
                return bodyCell(rowCol === colCol ? "—" : c ? fmt(c.r, 2) : "—", {
                  mono: true,
                });
              }),
            ],
          })
      ),
    ],
  });
}

function linearRegBlock(lr: LinearRegressionResult): Paragraph[] {
  return [
    textPara(
      `Linear regression: ${lr.outcome} = ${fmt(lr.intercept, 3)} + ${fmt(lr.slope, 3)} × ${lr.predictor} (n = ${lr.n})`
    ),
    textPara(
      `slope = ${fmt(lr.slope, 4)} (SE ${fmt(lr.seSlope, 4)}), t = ${fmt(lr.tSlope, 3)}, p = ${fmtP(lr.pValue)}; r = ${fmt(lr.r, 3)}, R² = ${fmt(lr.r2, 3)}`,
      { bold: true }
    ),
  ];
}

function logisticBlock(lr: LogisticRegressionResult): Paragraph[] {
  return [
    textPara(
      `Logistic regression: ${lr.outcome} (positive = "${lr.positiveValue}") ~ ${lr.predictor} (n = ${lr.n})`
    ),
    textPara(
      `slope (log-odds) = ${fmt(lr.slope, 4)}, OR = ${fmt(lr.oddsRatio, 3)} (95% CI ${fmt(lr.oddsRatioCi[0], 3)}–${fmt(lr.oddsRatioCi[1], 3)}), Z = ${fmt(lr.z, 3)}, p = ${fmtP(lr.pValue)}`,
      { bold: true }
    ),
    ...(lr.converged ? [] : [textPara("(Did not fully converge)")]),
  ];
}

function kaplanMeierBlock(km: KaplanMeierResult): (Paragraph | Table)[] {
  const out: (Paragraph | Table)[] = [];
  out.push(
    textPara(
      `Kaplan–Meier survival on ${km.timeColumn}, event = "${km.positiveEventValue}" in ${km.eventColumn}.`
    )
  );
  out.push(
    new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      rows: [
        new TableRow({
          children: ["Group", "n", "Events", "Median survival"].map(headerCell),
        }),
        ...km.groups.map(
          (g) =>
            new TableRow({
              children: [
                bodyCell(g.name),
                bodyCell(String(g.n), { mono: true }),
                bodyCell(String(g.events), { mono: true }),
                bodyCell(g.medianSurvival !== null ? fmt(g.medianSurvival) : "Not reached", {
                  mono: true,
                }),
              ],
            })
        ),
      ],
    })
  );
  if (km.logRank) {
    out.push(
      textPara(
        `Log-rank test: χ²(${km.logRank.df}) = ${fmt(km.logRank.chi2, 3)}, p = ${fmtP(km.logRank.pValue)}`,
        { bold: true }
      )
    );
  }
  return out;
}

function rocBlock(r: RocResult): Paragraph[] {
  return [
    textPara(
      `ROC analysis: ${r.outcome} (positive = "${r.positiveValue}") vs ${r.predictor}. n = ${r.n} (${r.positives} positive, ${r.negatives} negative).`
    ),
    textPara(`AUC = ${fmt(r.auc, 3)}`, { bold: true }),
    textPara(
      `Optimal threshold (Youden's J) = ${fmt(r.optimal.threshold, 3)}: sensitivity = ${fmt(r.optimal.sens, 3)}, specificity = ${fmt(r.optimal.spec, 3)}, PPV = ${fmt(r.optimal.ppv, 3)}, NPV = ${fmt(r.optimal.npv, 3)}.`
    ),
  ];
}

function normalityBlock(n: NormalityResult): Paragraph[] {
  return [
    textPara(`Jarque–Bera normality test on ${n.column} (n = ${n.n}).`),
    textPara(
      `mean = ${fmt(n.mean)}, SD = ${fmt(n.sd)}, skewness = ${fmt(n.skewness, 3)}, kurtosis = ${fmt(n.kurtosis, 3)}, JB = ${fmt(n.jb, 3)}, p = ${fmtP(n.pValue)}`,
      { bold: true }
    ),
    textPara(
      n.conclusion === "consistent_with_normal"
        ? "Conclusion: data are consistent with a normal distribution."
        : "Conclusion: data deviate significantly from normality. Consider non-parametric tests."
    ),
  ];
}

function boxplotTable(b: BoxplotResult): Table {
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      new TableRow({
        children: ["Group", "n", "Min", "Q1", "Median", "Q3", "Max", "Outliers"].map(
          headerCell
        ),
      }),
      ...b.groups.map(
        (g) =>
          new TableRow({
            children: [
              bodyCell(g.name),
              bodyCell(String(g.n), { mono: true }),
              bodyCell(fmt(g.min), { mono: true }),
              bodyCell(fmt(g.q1), { mono: true }),
              bodyCell(fmt(g.median), { mono: true }),
              bodyCell(fmt(g.q3), { mono: true }),
              bodyCell(fmt(g.max), { mono: true }),
              bodyCell(String(g.outliers.length), { mono: true }),
            ],
          })
      ),
    ],
  });
}
