import {
  AlignmentType,
  Document,
  HeadingLevel,
  Packer,
  PageBreak,
  Paragraph,
  TextRun,
} from "docx";
import { renderPrismaTextSummary, safeParsePrismaFlow } from "@/lib/prisma-flow";

export type ResearchExport = {
  title: string;
  kindLabel: string;
  authorName: string | null;
  university: string | null;
  specialty: string | null;
  studyType: string | null;
  language: string;
  citationStyle: string;
  sections: Array<{ title: string; content: string; metadataJson?: string | null }>;
};

/**
 * Render a research project to a Word .docx Buffer. Plain-prose paragraphs,
 * with simple bullet detection so lines starting with "- ", "* ", "• " or
 * "1.", "2.", … become list items. The cover page has the title, the user's
 * name, university, and a generated-by stamp.
 */
export async function renderResearchDocx(p: ResearchExport): Promise<Buffer> {
  const cover: Paragraph[] = [
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 1800, after: 400 },
      children: [
        new TextRun({
          text: p.kindLabel.toUpperCase(),
          bold: true,
          size: 22,
          color: "555555",
        }),
      ],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 200, after: 600 },
      children: [
        new TextRun({ text: p.title, bold: true, size: 44 }),
      ],
    }),
    p.authorName
      ? new Paragraph({
          alignment: AlignmentType.CENTER,
          spacing: { before: 400, after: 200 },
          children: [new TextRun({ text: p.authorName, size: 26 })],
        })
      : new Paragraph({}),
    p.university
      ? new Paragraph({
          alignment: AlignmentType.CENTER,
          spacing: { after: 100 },
          children: [new TextRun({ text: p.university, italics: true, size: 22 })],
        })
      : new Paragraph({}),
    p.specialty || p.studyType
      ? new Paragraph({
          alignment: AlignmentType.CENTER,
          spacing: { after: 100 },
          children: [
            new TextRun({
              text: [p.specialty, p.studyType].filter(Boolean).join(" · "),
              size: 22,
              color: "666666",
            }),
          ],
        })
      : new Paragraph({}),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 1200, after: 600 },
      children: [
        new TextRun({
          text: `Generated by MedExam Hub — Research Assistant · ${new Date().toLocaleDateString()}`,
          italics: true,
          size: 18,
          color: "888888",
        }),
      ],
    }),
    new Paragraph({ children: [new PageBreak()] }),
  ];

  const body: Paragraph[] = [];
  for (const section of p.sections) {
    body.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 400, after: 200 },
        children: [new TextRun({ text: section.title, bold: true, size: 32 })],
      })
    );

    // PRISMA flow + any future diagram sections: render the structured
    // summary as text. Embedding SVG-rendered images directly is in
    // scope for Phase 3 — for V2 the user will see a clean numbered
    // list they can paste a screenshot next to.
    const prismaData = section.metadataJson
      ? safeParsePrismaFlow(section.metadataJson)
      : null;
    const effectiveText = prismaData
      ? renderPrismaTextSummary(prismaData) +
        "\n\n[A visual PRISMA flow diagram is shown in the on-screen editor — paste a screenshot here.]"
      : section.content;

    for (const line of effectiveText.split(/\r?\n/)) {
      const trimmed = line.trim();
      if (trimmed.length === 0) {
        body.push(new Paragraph({}));
        continue;
      }
      const bulletMatch = /^[-•*]\s+(.*)/.exec(trimmed);
      const numberedMatch = /^\d+[.)]\s+(.*)/.exec(trimmed);
      if (bulletMatch) {
        body.push(
          new Paragraph({
            bullet: { level: 0 },
            spacing: { after: 100 },
            children: [new TextRun({ text: bulletMatch[1], size: 22 })],
          })
        );
        continue;
      }
      if (numberedMatch) {
        body.push(
          new Paragraph({
            numbering: { reference: "default-numbered", level: 0 },
            spacing: { after: 100 },
            children: [new TextRun({ text: numberedMatch[1], size: 22 })],
          })
        );
        continue;
      }
      // Sub-heading detection: a short line ending with ":" gets bolded.
      if (trimmed.length < 80 && trimmed.endsWith(":")) {
        body.push(
          new Paragraph({
            spacing: { before: 200, after: 100 },
            children: [
              new TextRun({ text: trimmed.replace(/:$/, ""), bold: true, size: 24 }),
            ],
          })
        );
        continue;
      }
      body.push(
        new Paragraph({
          spacing: { after: 140 },
          children: [new TextRun({ text: trimmed, size: 22 })],
        })
      );
    }
  }

  const doc = new Document({
    creator: p.authorName ?? "MedExam Hub",
    title: p.title,
    description: p.kindLabel,
    numbering: {
      config: [
        {
          reference: "default-numbered",
          levels: [
            {
              level: 0,
              format: "decimal",
              text: "%1.",
              alignment: AlignmentType.LEFT,
            },
          ],
        },
      ],
    },
    sections: [
      {
        properties: {},
        children: [...cover, ...body],
      },
    ],
  });

  return Buffer.from(await Packer.toBuffer(doc));
}
