export const SPECIALTIES = [
  "Allergy and Immunology",
  "Anatomy",
  "Anesthesiology",
  "Biochemistry",
  "Cardiology",
  "Cardiothoracic Surgery",
  "Dermatology",
  "Diabetic Foot",
  "Emergency Medicine",
  "Endocrinology",
  "Family Medicine",
  "Forensic Medicine",
  "Gastroenterology",
  "General Surgery",
  "Geriatrics",
  "Hematology",
  "ICU and Critical Care",
  "Infectious Diseases",
  "Internal Medicine",
  "Maxillofacial Surgery",
  "Medical Genetics",
  "Microbiology",
  "Molecular Biology",
  "Neonatology",
  "Nephrology",
  "Neurology",
  "Neurosurgery",
  "Nuclear Medicine",
  "Nursing",
  "Obstetrics and Gynecology",
  "Occupational Medicine",
  "Oncology",
  "Ophthalmology",
  "Orthopedics",
  "Otolaryngology (ENT)",
  "Pain Management",
  "Palliative Care",
  "Pathology",
  "Pediatric Surgery",
  "Pediatrics",
  "Pharmacology",
  "Physiology",
  "Plastic Surgery",
  "Psychiatry",
  "Public Health",
  "Pulmonology",
  "Radiology",
  "Rehabilitation Medicine",
  "Reproductive Medicine",
  "Rheumatology",
  "Sleep Medicine",
  "Sports Medicine",
  "Trauma Surgery",
  "Urology",
  "Vascular Surgery",
  "Wound Care",
] as const;

export type Specialty = (typeof SPECIALTIES)[number];
