import { redirect } from "next/navigation";
import { requireUser } from "@/lib/auth";
import { prisma } from "@/lib/db";
import PrintTrigger from "./PrintTrigger";

export const metadata = { title: "Print research project" };

export default async function PrintPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const user = await requireUser();

  const project = await prisma.researchProject.findUnique({
    where: { id },
    include: { sections: { orderBy: { orderIndex: "asc" } } },
  });
  if (!project || project.userId !== user.id) redirect("/research");

  const populatedSections = project.sections.filter((s) => s.content.trim().length > 0);
  const kindLabel = project.kind === "PROTOCOL" ? "Research Protocol" : "Thesis";
  const authorName = user.name ?? user.email.split("@")[0];

  return (
    <div className="mx-auto max-w-3xl bg-white px-4 py-10 text-zinc-900 sm:px-6 sm:py-12 print:px-0 print:py-0">
      <PrintTrigger />

      <div className="text-center print:mt-12">
        <p className="text-xs font-medium uppercase tracking-widest text-zinc-500">
          {kindLabel}
        </p>
        <h1 className="mt-3 text-3xl font-bold leading-tight sm:text-4xl">{project.title}</h1>
        <p className="mt-6 text-base">{authorName}</p>
        {project.university && <p className="mt-1 text-sm italic">{project.university}</p>}
        {(project.specialty || project.studyType) && (
          <p className="mt-1 text-sm text-zinc-600">
            {[project.specialty, project.studyType].filter(Boolean).join(" · ")}
          </p>
        )}
        <p className="mt-12 text-xs text-zinc-500">
          Generated by MedExam Hub · {new Date().toLocaleDateString()}
        </p>
      </div>

      <div className="mt-16 break-after-page" />

      <div className="space-y-10 print:space-y-8">
        {populatedSections.map((s) => (
          <section key={s.id} className="break-inside-avoid">
            <h2 className="text-xl font-bold tracking-tight border-b border-zinc-300 pb-2 mb-4 print:text-lg">
              {s.title}
            </h2>
            <div className="prose prose-zinc max-w-none whitespace-pre-wrap text-sm leading-relaxed">
              {s.content}
            </div>
          </section>
        ))}
      </div>
    </div>
  );
}
