import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { SPECIALTIES, SPECIALTY_SLUGS } from "./specialties";

// Pre-render every specialty at build time (handful of pages, all static).
export async function generateStaticParams() {
  return SPECIALTY_SLUGS.map((slug) => ({ slug }));
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  const data = SPECIALTIES[slug];
  if (!data) return {};
  const canonical = `https://medexamhub.org/specialty/${slug}`;
  return {
    title: data.title,
    description: data.metaDescription,
    alternates: { canonical },
    openGraph: {
      type: "website",
      title: data.title,
      description: data.metaDescription,
      url: canonical,
      images: [{ url: "/logo.png", width: 512, height: 512 }],
    },
    twitter: {
      card: "summary_large_image",
      title: data.title,
      description: data.metaDescription,
    },
  };
}

export default async function SpecialtyPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const data = SPECIALTIES[slug];
  if (!data) return notFound();

  // FAQPage JSON-LD makes our FAQ eligible for Google's rich-result
  // expandable card on this page in search results.
  const faqJsonLd = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: data.faq.map((item) => ({
      "@type": "Question",
      name: item.q,
      acceptedAnswer: {
        "@type": "Answer",
        text: item.a,
      },
    })),
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
      />

      <div className="mx-auto max-w-4xl px-4 py-10 sm:px-6 sm:py-14">
        {/* Hero */}
        <div className="text-center">
          <p className="text-xs font-semibold uppercase tracking-[0.18em] text-blue-600">
            Specialty
          </p>
          <h1 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">
            {data.heading}
          </h1>
          <p className="mx-auto mt-3 max-w-2xl text-base text-zinc-600 dark:text-zinc-400">
            {data.tagline}
          </p>
          <div className="mt-6 flex flex-wrap items-center justify-center gap-3">
            <Link
              href="/exam/new"
              className="rounded-md bg-blue-600 px-5 py-2.5 text-sm font-semibold text-white hover:bg-blue-700"
            >
              Generate a {slug} exam →
            </Link>
            <Link
              href="/plans"
              className="rounded-md border border-zinc-300 px-5 py-2.5 text-sm font-semibold hover:bg-zinc-50 dark:border-zinc-700 dark:hover:bg-zinc-800"
            >
              View plans
            </Link>
          </div>
        </div>

        {/* Intro */}
        <section className="mt-10 rounded-2xl border border-zinc-200 bg-white p-6 dark:border-zinc-800 dark:bg-zinc-900 sm:p-8">
          <p className="text-base leading-relaxed text-zinc-700 dark:text-zinc-300">
            {data.intro}
          </p>

          <h2 className="mt-6 text-sm font-semibold uppercase tracking-wide text-zinc-500">
            What's covered
          </h2>
          <ul className="mt-3 grid gap-2 text-sm sm:grid-cols-2">
            {data.highlights.map((h) => (
              <li key={h} className="flex gap-2">
                <span className="text-emerald-600">✓</span>
                <span>{h}</span>
              </li>
            ))}
          </ul>

          <h2 className="mt-6 text-sm font-semibold uppercase tracking-wide text-zinc-500">
            Calibrated to these exams
          </h2>
          <div className="mt-3 flex flex-wrap gap-2">
            {data.exams.map((e) => (
              <span
                key={e}
                className="rounded-full border border-zinc-200 bg-zinc-50 px-3 py-1 text-xs font-medium dark:border-zinc-700 dark:bg-zinc-800/60"
              >
                {e}
              </span>
            ))}
          </div>
        </section>

        {/* Sample questions */}
        <section className="mt-10">
          <h2 className="text-xl font-semibold tracking-tight">
            Sample questions
          </h2>
          <p className="mt-1 text-sm text-zinc-500">
            Generated by our AI. Sign up to get unlimited fresh questions on
            demand.
          </p>
          <div className="mt-4 space-y-4">
            {data.sampleQuestions.map((q, i) => (
              <details
                key={i}
                className="group rounded-xl border border-zinc-200 bg-white p-4 open:border-blue-300 dark:border-zinc-800 dark:bg-zinc-900 dark:open:border-blue-700 sm:p-5"
              >
                <summary className="flex cursor-pointer items-start gap-2 text-sm font-medium">
                  <span className="text-zinc-400">Q{i + 1}.</span>
                  <span className="flex-1">{q.question}</span>
                  <span className="text-xs text-blue-600 group-open:hidden">Show answer</span>
                  <span className="hidden text-xs text-zinc-400 group-open:inline">Hide</span>
                </summary>
                <div className="mt-3 border-t border-zinc-200 pt-3 text-sm text-zinc-700 dark:border-zinc-800 dark:text-zinc-300">
                  <span className="font-semibold text-emerald-700 dark:text-emerald-400">Answer: </span>
                  {q.answer}
                </div>
              </details>
            ))}
          </div>
        </section>

        {/* FAQ */}
        <section className="mt-10">
          <h2 className="text-xl font-semibold tracking-tight">FAQ</h2>
          <div className="mt-4 space-y-3">
            {data.faq.map((item, i) => (
              <details
                key={i}
                className="rounded-xl border border-zinc-200 bg-white p-4 dark:border-zinc-800 dark:bg-zinc-900"
              >
                <summary className="cursor-pointer text-sm font-semibold">
                  {item.q}
                </summary>
                <p className="mt-2 text-sm text-zinc-700 dark:text-zinc-300">
                  {item.a}
                </p>
              </details>
            ))}
          </div>
        </section>

        {/* CTA */}
        <section className="mt-12 rounded-2xl border border-blue-200 bg-blue-50 p-6 text-center dark:border-blue-900 dark:bg-blue-950/40 sm:p-8">
          <h2 className="text-xl font-semibold tracking-tight">
            Start your first {slug} exam in 30 seconds
          </h2>
          <p className="mt-2 text-sm text-zinc-600 dark:text-zinc-400">
            Free plan includes 20 questions/month. Paid plans from 299 EGP/mo
            unlock unlimited topics, image generation, and PDF export.
          </p>
          <div className="mt-5 flex flex-wrap items-center justify-center gap-3">
            <Link
              href="/signup?next=/exam/new"
              className="rounded-md bg-blue-600 px-5 py-2.5 text-sm font-semibold text-white hover:bg-blue-700"
            >
              Start free
            </Link>
            <Link
              href="/plans"
              className="rounded-md border border-zinc-300 px-5 py-2.5 text-sm font-semibold hover:bg-white dark:border-zinc-700 dark:hover:bg-zinc-900"
            >
              Compare plans
            </Link>
          </div>
        </section>

        {/* Other specialties */}
        <section className="mt-12 text-center">
          <h2 className="text-sm font-semibold uppercase tracking-wide text-zinc-500">
            Other specialties
          </h2>
          <div className="mt-3 flex flex-wrap items-center justify-center gap-2">
            {SPECIALTY_SLUGS.filter((s) => s !== slug).map((s) => (
              <Link
                key={s}
                href={`/specialty/${s}`}
                className="rounded-full border border-zinc-300 px-3 py-1 text-xs font-medium capitalize hover:bg-zinc-50 dark:border-zinc-700 dark:hover:bg-zinc-800"
              >
                {s}
              </Link>
            ))}
          </div>
        </section>
      </div>
    </>
  );
}
