// Per-specialty content for the landing-page template. Keep this as plain
// data (not MDX or CMS) until we have ~10+ specialties — at that point the
// duplication justifies a content layer. For now the simplest thing that
// could possibly work.
//
// Each specialty's text is hand-tuned for SEO long-tail queries Egyptian
// medical students actually search for ("MRCP cardiology questions",
// "pediatrics OSCE prep", "surgery viva exam", etc.). Each page targets
// the brand name + the specialty + the exam keyword. Avoid keyword
// stuffing — the body reads naturally.

export type SpecialtyContent = {
  slug: string;
  title: string;
  /** SEO meta description, 150-160 chars. */
  metaDescription: string;
  /** H1 shown on the page. */
  heading: string;
  /** One-line subhead under the H1. */
  tagline: string;
  /** Hero paragraph — 80-160 words. The first 60 words matter most for SEO. */
  intro: string;
  /** 3-5 bullet points of what's covered. */
  highlights: string[];
  /** 4-6 sample question titles. Real Q&A drives time-on-page = ranking boost. */
  sampleQuestions: { question: string; answer: string }[];
  /** Common exam names this specialty appears in. Shown as pill chips. */
  exams: string[];
  /** FAQ items rendered with JSON-LD FAQ schema. */
  faq: { q: string; a: string }[];
};

export const SPECIALTIES: Record<string, SpecialtyContent> = {
  cardiology: {
    slug: "cardiology",
    title: "Cardiology Exam Prep — AI Questions & Mock Tests | MedExam Hub",
    metaDescription:
      "AI-generated cardiology questions for MRCP, MRCS, USMLE, PLAB and Egyptian boards. ECG interpretation, heart failure, arrhythmias, coronary artery disease — practice unlimited.",
    heading: "Cardiology exam preparation, generated by AI",
    tagline:
      "Unlimited cardiology MCQs across ECG, arrhythmias, heart failure, valvular disease and more — tuned to your level.",
    intro:
      "Cardiology is the backbone of every internal medicine exam. Whether you're prepping for MRCP Part 1, USMLE Step 2 CK, or the Egyptian Board of Internal Medicine, you need to drill the same high-yield patterns: ECG morphology, heart failure pharmacology, valvular lesions, ACS management. MedExam Hub generates fresh cardiology questions on demand — choose your difficulty, your sub-topic (ischaemia, congenital, electrophysiology), the number of questions, and whether you want clinical-vignette MCQs or short-notes format. Every question comes with a worked explanation and learning points so you understand the why, not just the answer.",
    highlights: [
      "ECG interpretation drills with rhythm-strip images",
      "Heart-failure pharmacology and ACE-i / ARB / SGLT2i decisions",
      "Arrhythmia recognition: AF, VT, AVNRT, heart block",
      "Coronary artery disease — STEMI, NSTEMI, ACS pathways",
      "Valvular disease, congenital heart, infective endocarditis",
    ],
    sampleQuestions: [
      {
        question:
          "A 68-year-old man presents with crushing central chest pain and ST elevation in leads II, III, aVF. Which coronary artery is most likely occluded?",
        answer:
          "Right coronary artery (RCA). Inferior STEMI pattern (II, III, aVF) almost always reflects RCA occlusion. Check V4R for right ventricular involvement before giving nitrates.",
      },
      {
        question:
          "Which medication has been shown to reduce mortality in HFrEF regardless of diabetic status?",
        answer:
          "SGLT2 inhibitors (dapagliflozin, empagliflozin). DAPA-HF and EMPEROR-Reduced demonstrated mortality benefit in HFrEF irrespective of diabetes.",
      },
      {
        question:
          "A 45-year-old has new-onset AF with normal LV function and no structural heart disease. CHA₂DS₂-VASc = 1 (hypertension). Anticoagulation?",
        answer:
          "Anticoagulation is reasonable but optional. Score of 1 (non-female) is the borderline zone — discuss bleeding risk via HAS-BLED and patient preference.",
      },
      {
        question:
          "Which murmur is best heard at the apex, radiating to the axilla, and louder on expiration?",
        answer:
          "Mitral regurgitation. Pan-systolic, apex-axilla radiation, louder on expiration. Differentiate from VSD (left sternal edge) and HOCM (no axillary radiation).",
      },
    ],
    exams: ["MRCP", "USMLE Step 2 CK", "PLAB 1", "Egyptian Board IM", "MRCS Part A"],
    faq: [
      {
        q: "How many cardiology questions can I generate per month on the free plan?",
        a: "Free plan includes 20 questions/month across all specialties. Basic (299 EGP/mo) gives you 400 questions; Pro (699 EGP/mo) 1,500 questions; Premium (1,099 EGP/mo) 5,000 questions.",
      },
      {
        q: "Are the cardiology questions calibrated to a specific exam?",
        a: "You pick the exam style when generating. We support MRCP, MRCS, USMLE, PLAB, and Egyptian board difficulty levels. The AI adjusts vignette length, MCQ complexity, and clinical detail.",
      },
      {
        q: "Can I review my mistakes later?",
        a: "Yes. Every exam is saved to your history and incorrect answers flow into the spaced-repetition system at /review, so you re-encounter them at scientifically-spaced intervals.",
      },
      {
        q: "Do you cover ECG interpretation with images?",
        a: "Yes — opt into image generation when creating an exam and the AI will include rhythm strips and 12-lead ECG images where clinically relevant.",
      },
    ],
  },

  pediatrics: {
    slug: "pediatrics",
    title: "Pediatrics Exam Prep — AI Questions & Mock Tests | MedExam Hub",
    metaDescription:
      "AI-generated pediatrics questions covering neonatology, growth & development, infectious diseases, vaccinations, and Egyptian Board paediatrics MCQs.",
    heading: "Pediatrics exam preparation, generated by AI",
    tagline:
      "Unlimited paediatric MCQs across neonatology, growth & development, infectious disease, paediatric emergencies, and more.",
    intro:
      "Paediatrics covers everything from neonatal resuscitation to adolescent gynaecology. Whether you're prepping for MRCPCH, USMLE Step 2 CK paeds questions, the Egyptian Board of Paediatrics, or a paediatric residency entry exam, you need broad coverage and the latest guidelines on vaccination schedules, growth charts, and developmental milestones. MedExam Hub generates fresh paediatric questions on demand — choose your sub-topic (neonatology, cardiology, gastroenterology, infectious disease), your difficulty, and your question format. Every answer comes with a worked explanation and key learning points.",
    highlights: [
      "Neonatal resuscitation, jaundice, RDS, NEC",
      "Growth and developmental milestones (red flags)",
      "Egyptian vaccination schedule + WHO recommendations",
      "Paediatric infectious disease — meningitis, sepsis, common rashes",
      "Paediatric emergencies — DKA, status asthmaticus, anaphylaxis",
    ],
    sampleQuestions: [
      {
        question:
          "A 6-month-old has a head circumference at the 3rd centile (was 50th at birth). Most appropriate next step?",
        answer:
          "Urgent neuroimaging. Crossing centiles downwards in head circumference suggests microcephaly developing post-natally — needs neurology workup including MRI brain.",
      },
      {
        question:
          "A 2-year-old with barking cough, stridor at rest, and respiratory distress. First-line management?",
        answer:
          "Nebulised adrenaline + oral or IM dexamethasone. Moderate-severe croup. Avoid agitating the child — IV access not first priority. Hospital admission if stridor persists at rest.",
      },
      {
        question:
          "A neonate is jaundiced at 18 hours of life. What's the most important investigation?",
        answer:
          "Direct Coombs test (DAT) + total/conjugated bilirubin + blood group. Jaundice <24 hours is haemolytic until proven otherwise — most commonly ABO or Rhesus incompatibility.",
      },
      {
        question:
          "Which vaccine in the Egyptian schedule is given at 9 months?",
        answer:
          "Measles vaccine (first dose). Second dose typically at 18 months in MMR form. Egypt follows a modified WHO schedule; check the latest MoH circular before exams.",
      },
    ],
    exams: ["MRCPCH", "USMLE Step 2 CK", "PLAB 1", "Egyptian Board Paediatrics"],
    faq: [
      {
        q: "Do questions follow the Egyptian Board of Paediatrics syllabus?",
        a: "Yes — select 'Egyptian Board' as the exam style and questions will be tuned to the Egyptian curriculum including local vaccination schedules and common presentations.",
      },
      {
        q: "Are vaccination schedules up to date?",
        a: "We update the AI's knowledge base regularly, but always cross-check with the latest Egyptian Ministry of Health circular before your exam date.",
      },
      {
        q: "Can I generate paediatric OSCE-style cases?",
        a: "Short-notes format gives you longer clinical vignettes that work well for OSCE prep, alongside standard MCQs.",
      },
      {
        q: "Do you include images of paediatric rashes / X-rays?",
        a: "Opt into image generation and you'll get AI-generated illustrations of common dermatology findings and radiographic patterns.",
      },
    ],
  },

  surgery: {
    slug: "surgery",
    title: "General Surgery Exam Prep — AI Questions & Mock Tests | MedExam Hub",
    metaDescription:
      "AI-generated surgery questions for MRCS Part A & B, USMLE, PLAB, and Egyptian Board of General Surgery. Acute abdomen, trauma, vascular, oncology MCQs.",
    heading: "Surgery exam preparation, generated by AI",
    tagline:
      "MRCS Part A, Part B, USMLE surgery, PLAB and Egyptian Board questions across acute abdomen, trauma, vascular, oncology and more.",
    intro:
      "General surgery exams span basic sciences, applied anatomy, operative principles, and clinical decision-making. MRCS Part A demands rapid-fire single-best-answer questions across anatomy, physiology, and pathology; Part B and the Egyptian Board favour applied-knowledge vignettes around acute presentations and pre/post-op management. MedExam Hub generates fresh surgical questions on demand — pick anatomy, peri-operative care, acute abdomen, trauma, vascular, breast and endocrine, or oncology. Every answer comes with a worked explanation that ties the question back to the underlying principle, so you build intuition rather than rote-memorising.",
    highlights: [
      "MRCS Part A applied basic science (anatomy, physiology, pathology, microbiology)",
      "Acute abdomen — appendicitis, perforation, bowel obstruction, biliary",
      "Trauma — ATLS principles, damage control, FAST, primary survey",
      "Vascular surgery — limb ischaemia, AAA, carotid disease",
      "Breast and endocrine — staging, surgical oncology principles",
    ],
    sampleQuestions: [
      {
        question:
          "A 65-year-old with sudden severe abdominal pain, atrial fibrillation, soft abdomen on examination, raised lactate. Most likely diagnosis?",
        answer:
          "Acute mesenteric ischaemia. Classic triad: severe pain out of proportion to clinical findings, AF (embolic source), raised lactate. CT angiography urgently. Surgical emergency.",
      },
      {
        question:
          "In the MRCS-style ATLS primary survey, what's the priority after airway and breathing?",
        answer:
          "Circulation. C in ABCDE. Control external haemorrhage, assess perfusion, gain large-bore IV access ×2, start fluid/blood resuscitation. Then D (disability/GCS) and E (exposure).",
      },
      {
        question:
          "A 45-year-old man with painless obstructive jaundice and a palpable gallbladder. Most likely diagnosis?",
        answer:
          "Pancreatic head carcinoma (Courvoisier's sign). Painless jaundice with palpable gallbladder is unlikely to be gallstones (which scar the gallbladder). Urgent CT pancreas + CA 19-9.",
      },
      {
        question:
          "Which artery is the dominant supply to the foregut?",
        answer:
          "Coeliac trunk. Foregut = lower oesophagus to second part of duodenum (including liver, spleen, pancreas). Midgut → SMA. Hindgut → IMA. Common MRCS Part A anatomy question.",
      },
    ],
    exams: ["MRCS Part A", "MRCS Part B", "USMLE Step 2 CK", "PLAB 1", "Egyptian Board GS"],
    faq: [
      {
        q: "Are questions calibrated to MRCS difficulty?",
        a: "Yes — pick MRCS as the exam style. Part A questions emphasise applied basic sciences (anatomy, physiology, pathology); we tune vignette length and complexity accordingly.",
      },
      {
        q: "Do you cover surgical anatomy with diagrams?",
        a: "Opt into image generation when creating an exam and you'll get AI-generated anatomical illustrations alongside the vignettes.",
      },
      {
        q: "Can I focus on specific topics like trauma or vascular?",
        a: "Yes. When generating an exam you can specify the sub-topic (e.g. 'trauma resuscitation', 'vascular emergencies', 'breast surgery') and the AI restricts questions to that area.",
      },
      {
        q: "Is the Egyptian Board GS syllabus covered?",
        a: "Yes — Egyptian Board mode tunes questions to the local syllabus including common presentations and the operative procedures expected of a board candidate.",
      },
    ],
  },
};

export const SPECIALTY_SLUGS = Object.keys(SPECIALTIES);
