import type { Metadata } from "next";
import { Geist } from "next/font/google";
import Link from "next/link";
import Image from "next/image";
import "./globals.css";
import { getCurrentUser } from "@/lib/auth";
import { logoutAction } from "@/app/actions/auth";
import WhatsAppButton from "@/components/WhatsAppButton";
import ServiceWorkerRegister from "@/components/ServiceWorkerRegister";
import LanguageSwitcher from "@/components/LanguageSwitcher";
import MobileNav from "@/components/MobileNav";
import NotificationBell from "@/components/NotificationBell";
import { getUnreadCount } from "@/lib/notifications";
import { isRtl } from "@/lib/i18n";
import { getLocale, getTranslations } from "@/lib/i18n-server";
import { isAdmin } from "@/lib/admin";
import { NAV_COLOR_DESKTOP, type NavColor } from "@/lib/nav-colors";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const SITE_URL = "https://medexamhub.org";
const SITE_NAME = "MedExam Hub";
const SITE_TAGLINE = "AI-powered medical exam prep";
const SITE_DESCRIPTION =
  "AI-generated medical exams, mock tests with timers, a free medical library, study notes, and a community for medical students, residents, and doctors. MRCP, MRCS, USMLE, PLAB, and Egyptian board prep.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: `${SITE_NAME} — ${SITE_TAGLINE}`,
    template: `%s | ${SITE_NAME}`,
  },
  description: SITE_DESCRIPTION,
  applicationName: SITE_NAME,
  keywords: [
    "medical exam prep",
    "MRCP",
    "MRCS",
    "USMLE",
    "PLAB",
    "medical board",
    "mock exam",
    "AI medical questions",
    "medical student",
    "doctor exam",
    "Egypt medical",
  ],
  authors: [{ name: SITE_NAME, url: SITE_URL }],
  creator: SITE_NAME,
  publisher: SITE_NAME,
  alternates: { canonical: SITE_URL },
  openGraph: {
    type: "website",
    siteName: SITE_NAME,
    title: `${SITE_NAME} — ${SITE_TAGLINE}`,
    description: SITE_DESCRIPTION,
    url: SITE_URL,
    locale: "en_US",
    images: [
      {
        url: "/logo.png",
        width: 512,
        height: 512,
        alt: SITE_NAME,
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: `${SITE_NAME} — ${SITE_TAGLINE}`,
    description: SITE_DESCRIPTION,
    images: ["/logo.png"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  // PWA / installable web app metadata. Manifest lives at /manifest.webmanifest
  // (generated by src/app/manifest.ts); apple-touch-icon tells iOS Safari
  // which icon to use when the user picks "Add to Home Screen".
  manifest: "/manifest.webmanifest",
  appleWebApp: {
    capable: true,
    title: SITE_NAME,
    statusBarStyle: "default",
    startupImage: ["/logo.png"],
  },
  icons: {
    icon: [
      { url: "/logo.png", type: "image/png" },
      { url: "/logo.webp", type: "image/webp" },
    ],
    apple: [{ url: "/logo.png", sizes: "180x180", type: "image/png" }],
  },
};

// JSON-LD Organization schema — drives Google's "knowledge panel" card with
// our logo, name, and contact info on brand-name searches. Injected as a
// <script type="application/ld+json"> below.
const ORGANIZATION_LD = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: SITE_NAME,
  url: SITE_URL,
  logo: `${SITE_URL}/logo.png`,
  description: SITE_DESCRIPTION,
  email: "info@medexamhub.org",
  address: {
    "@type": "PostalAddress",
    addressLocality: "Cairo",
    addressCountry: "EG",
  },
  sameAs: [
    // Add real social profile URLs here as they go live; Google uses these
    // for the knowledge panel social links row.
    "https://wa.me/201226218004",
  ],
};

// Theme + viewport — separate export in Next.js 16. The theme_color drives
// the Android Chrome status-bar tint when the PWA is installed.
export const viewport = {
  themeColor: "#2563eb",
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover" as const,
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const [user, locale] = await Promise.all([getCurrentUser(), getLocale()]);
  const t = getTranslations(locale);
  const dir = isRtl(locale) ? "rtl" : "ltr";
  const showAdmin = user ? isAdmin(user) : false;
  // Defensive: if the Notification table is missing or any other DB issue
  // arises, never crash the whole app shell. The bell just shows 0.
  const unreadCount = user
    ? await getUnreadCount(user.id).catch(() => 0)
    : 0;

  type NavItem = {
    href: string;
    label: string;
    emphasis?: "primary" | "admin" | "muted";
    color?: NavColor;
    section?: string;
    pinned?: boolean;
  };
  const mobileItems: NavItem[] = user
    ? [
        // Main study actions — what the user opens the app to do.
        { href: "/exam/new", label: t.nav.generate, emphasis: "primary", section: "Study" },
        { href: "/mock", label: "🎯 Mock exam", color: "rose", section: "Study" },
        { href: "/notes", label: "📝 Study notes", color: "violet", section: "Study" },
        { href: "/review", label: "📚 Review", color: "amber", section: "Study" },
        { href: "/dashboard", label: t.nav.dashboard, color: "blue", section: "Study" },
        // Content libraries.
        { href: "/library", label: t.nav.library, color: "emerald", section: "Library" },
        { href: "/courses", label: "Courses", color: "cyan", section: "Library" },
        { href: "/research", label: "Research & Stats", color: "violet", section: "Library" },
        // Social.
        { href: "/community", label: "Community", color: "rose", section: "Social" },
        { href: `/u/${user.id}`, label: "My profile", color: "rose", section: "Social" },
        // Account / billing.
        { href: "/plans", label: t.nav.plans, color: "indigo", section: "Account" },
        { href: "/account/subscription", label: t.account.manageLink, color: "zinc", section: "Account" },
        ...(showAdmin
          ? ([{ href: "/admin", label: "Admin", emphasis: "admin", section: "Account" }] as NavItem[])
          : []),
      ]
    : [
        // Discovery for unsigned visitors.
        { href: "/plans", label: t.nav.plans, color: "indigo", section: "Browse" },
        { href: "/library", label: t.nav.library, color: "emerald", section: "Browse" },
        { href: "/courses", label: "Courses", color: "cyan", section: "Browse" },
        { href: "/community", label: "Community", color: "rose", section: "Browse" },
        // Pinned auth row sticks at the bottom of the menu — the
        // primary call-to-action on every page for guests.
        { href: "/login", label: t.nav.signin, color: "blue", pinned: true },
        { href: "/signup", label: t.nav.signup, emphasis: "primary", pinned: true },
      ];

  const pill = "rounded-full px-4 py-2 text-sm font-semibold transition";

  return (
    <html lang={locale} dir={dir} className={`${geistSans.variable} h-full antialiased`}>
      <head>
        {/* JSON-LD Organization schema for Google knowledge panel + rich
            results. Static so we can ship it as a <script> in the head. */}
        <script
          type="application/ld+json"
          // Safe: ORGANIZATION_LD is a hand-authored object, no user input.
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(ORGANIZATION_LD),
          }}
        />
        {/* Strip browser-extension-injected attributes (Bitdefender's bis_skin_checked, etc.)
            before React hydrates. Dev-only noise; does not affect functionality. */}
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){var s=function(){document.querySelectorAll('[bis_skin_checked],[bis_register],[__processed_]').forEach(function(e){e.removeAttribute('bis_skin_checked');e.removeAttribute('bis_register');});};try{new MutationObserver(s).observe(document.documentElement,{subtree:true,attributes:true,attributeFilter:['bis_skin_checked','bis_register']});s();}catch(_){};})();`,
          }}
        />
      </head>
      <body
        suppressHydrationWarning
        className="min-h-full flex flex-col bg-zinc-50 text-zinc-900 dark:bg-zinc-950 dark:text-zinc-100"
      >
        <header className="sticky top-0 z-30 border-b border-zinc-200 bg-white/90 backdrop-blur dark:bg-slate-900/80 dark:border-slate-800/60">
          <div className="mx-auto max-w-6xl px-4 py-3 sm:px-6">
            {/* Top row: logo + wordmark on the left, action cluster on the right */}
            <div className="flex items-center justify-between gap-3">
              <Link
                href="/"
                title="Back to home"
                aria-label="MedExam Hub — back to home"
                className="flex items-center gap-3 transition hover:opacity-90"
              >
                {/* Wrapper gives the logo a clearly visible white card
                    in dark mode so its dark-blue brain illustration
                    doesn't blend into the slate header. */}
                <span className="inline-flex items-center justify-center rounded-lg dark:bg-white dark:p-1.5 dark:shadow-sm dark:ring-1 dark:ring-white/30">
                  <Image
                    src="/logo.webp"
                    alt=""
                    width={72}
                    height={72}
                    className="h-12 w-auto sm:h-16"
                    priority
                  />
                </span>
                <span className="whitespace-nowrap text-lg font-bold tracking-tight text-zinc-900 dark:text-zinc-100 sm:text-xl">
                  MedExam Hub
                </span>
              </Link>

              <div className="flex items-center gap-2">
                {user ? (
                  <>
                    <Link
                      href="/exam/new"
                      className="hidden rounded-full bg-blue-600 px-5 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-blue-700 md:inline-flex"
                    >
                      {t.nav.generate}
                    </Link>
                    <NotificationBell unread={unreadCount} />
                    <form action={logoutAction} className="hidden md:block">
                      <button
                        type="submit"
                        className="rounded-full px-4 py-2 text-sm font-semibold text-zinc-500 transition hover:bg-zinc-100 hover:text-zinc-900 dark:hover:bg-zinc-800 dark:hover:text-zinc-100"
                      >
                        {t.nav.signout}
                      </button>
                    </form>
                    <LanguageSwitcher current={locale} />
                    <MobileNav
                      items={mobileItems}
                      signedIn={true}
                      signoutLabel={t.nav.signout}
                    />
                  </>
                ) : (
                  <>
                    <Link
                      href="/plans"
                      className={`hidden md:inline-flex ${pill} ${NAV_COLOR_DESKTOP.indigo}`}
                    >
                      {t.nav.plans}
                    </Link>
                    {/* Sign in + Start free move to their own centered
                        row on mobile (below the logo). Hidden here on
                        small screens; visible inline on md+. */}
                    <Link
                      href="/login"
                      className="hidden text-sm font-semibold text-zinc-700 hover:text-blue-600 dark:text-zinc-300 md:inline-flex"
                    >
                      {t.nav.signin}
                    </Link>
                    <Link
                      href="/signup"
                      className="hidden rounded-full bg-blue-600 px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-blue-700 md:inline-flex md:px-5"
                    >
                      {t.nav.signup}
                    </Link>
                    <LanguageSwitcher current={locale} />
                  </>
                )}
              </div>
            </div>
            {!user && (
              <div className="mt-3 flex items-center justify-center gap-3 md:hidden">
                <Link
                  href="/login"
                  className="text-sm font-semibold text-zinc-700 hover:text-blue-600 dark:text-zinc-300"
                >
                  {t.nav.signin}
                </Link>
                <Link
                  href="/signup"
                  className="rounded-full bg-blue-600 px-5 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-blue-700"
                >
                  {t.nav.signup}
                </Link>
              </div>
            )}

            {/* Bottom row: navigation pills (signed-in users, desktop only). */}
            {user && (
              <nav className="mt-3 hidden flex-wrap items-center gap-2 text-sm md:flex lg:gap-2.5">
                <Link href="/plans" className={`${pill} ${NAV_COLOR_DESKTOP.indigo}`}>
                  {t.nav.plans}
                </Link>
                <Link href="/dashboard" className={`${pill} ${NAV_COLOR_DESKTOP.blue}`}>
                  {t.nav.dashboard}
                </Link>
                <Link href="/mock" className={`${pill} ${NAV_COLOR_DESKTOP.rose}`}>
                  🎯 Mock exam
                </Link>
                <Link href="/notes" className={`${pill} ${NAV_COLOR_DESKTOP.violet}`}>
                  📝 Notes
                </Link>
                <Link href="/review" className={`${pill} ${NAV_COLOR_DESKTOP.amber}`}>
                  📚 Review
                </Link>
                <Link href="/research" className={`${pill} ${NAV_COLOR_DESKTOP.violet}`}>
                  Research &amp; Stats
                </Link>
                <Link href="/community" className={`${pill} ${NAV_COLOR_DESKTOP.rose}`}>
                  Community
                </Link>
                <Link href="/library" className={`${pill} ${NAV_COLOR_DESKTOP.emerald}`}>
                  {t.nav.library}
                </Link>
                <Link href="/courses" className={`${pill} ${NAV_COLOR_DESKTOP.cyan}`}>
                  Courses
                </Link>
                {showAdmin && (
                  <Link href="/admin" className={`${pill} ${NAV_COLOR_DESKTOP.amber}`}>
                    Admin
                  </Link>
                )}
                <Link
                  href={`/u/${user.id}`}
                  className={`${pill} ${NAV_COLOR_DESKTOP.rose}`}
                >
                  My profile
                </Link>
                <Link
                  href="/account/subscription"
                  className={`${pill} ${NAV_COLOR_DESKTOP.zinc}`}
                >
                  {t.account.manageLink}
                </Link>
              </nav>
            )}
          </div>
        </header>
        <main className="flex-1">{children}</main>
        <footer className="border-t border-zinc-200 pb-24 text-zinc-600 dark:border-slate-800/60 dark:text-slate-400 sm:pb-8">
          <div className="mx-auto grid max-w-6xl gap-10 px-4 py-12 sm:px-6 sm:py-14 md:grid-cols-3">
            {/* Brand block */}
            <div className="md:max-w-xs">
              <div className="flex items-center gap-3">
                <span className="inline-flex items-center justify-center rounded-md dark:bg-white dark:p-1">
                  <Image
                    src="/logo.webp"
                    alt=""
                    width={56}
                    height={56}
                    className="h-10 w-auto"
                  />
                </span>
                <span className="text-base font-bold tracking-tight text-zinc-900 dark:text-zinc-100">
                  MedExam Hub
                </span>
              </div>
              <p className="mt-3 text-xs leading-relaxed">
                {t.footer.disclaimer}
              </p>
              <p className="mt-3 inline-flex items-center gap-1 text-xs text-zinc-500 dark:text-slate-500">
                <span aria-hidden>📍</span> Cairo, Egypt
              </p>
              <a
                href="mailto:info@medexamhub.org"
                className="mt-2 inline-flex items-center gap-1 text-xs text-zinc-500 hover:text-blue-600 dark:text-slate-500 dark:hover:text-cyan-400"
              >
                <span aria-hidden>✉</span> info@medexamhub.org
              </a>
              <div className="mt-4 flex gap-2">
                <a
                  href="https://wa.me/201226218004"
                  target="_blank"
                  rel="noopener noreferrer"
                  aria-label="Chat on WhatsApp"
                  className="grid h-9 w-9 place-items-center rounded-full border border-zinc-200 text-zinc-500 transition hover:border-emerald-400 hover:text-emerald-600 dark:border-slate-700 dark:text-slate-400 dark:hover:border-emerald-500 dark:hover:text-emerald-400"
                >
                  <svg viewBox="0 0 24 24" className="h-4 w-4" fill="currentColor" aria-hidden>
                    <path d="M.057 24l1.687-6.163c-1.041-1.804-1.588-3.849-1.587-5.946.003-6.556 5.338-11.891 11.893-11.891 3.181.001 6.167 1.24 8.413 3.488 2.245 2.248 3.481 5.236 3.48 8.414-.003 6.557-5.338 11.892-11.893 11.892-1.99-.001-3.951-.5-5.688-1.448L.057 24zm6.597-3.807c1.676.995 3.276 1.591 5.392 1.592 5.448 0 9.886-4.434 9.889-9.885.002-5.462-4.415-9.89-9.881-9.892-5.452 0-9.887 4.434-9.889 9.884-.001 2.225.651 3.891 1.746 5.634l-.999 3.648 3.742-.981zm11.387-5.464c-.074-.124-.272-.198-.57-.347-.297-.149-1.758-.868-2.031-.967-.272-.099-.47-.149-.669.149-.198.297-.768.967-.941 1.165-.173.198-.347.223-.644.074-.297-.149-1.255-.462-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.297-.347.446-.521.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.521-.074-.149-.669-1.611-.916-2.206-.242-.579-.487-.501-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.095 3.2 5.076 4.487.709.306 1.263.489 1.694.626.712.226 1.36.194 1.872.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413z" />
                  </svg>
                </a>
              </div>
            </div>

            {/* PLATFORM column */}
            <div>
              <h3 className="text-[11px] font-semibold uppercase tracking-[0.14em] text-zinc-500 dark:text-slate-400">
                Platform
              </h3>
              <ul className="mt-4 space-y-2 text-sm">
                <li><Link href="/" className="hover:text-zinc-900 dark:hover:text-zinc-100">Home</Link></li>
                <li><Link href="/plans" className="hover:text-zinc-900 dark:hover:text-zinc-100">{t.footer.about === "About" ? "Pricing" : t.nav.plans}</Link></li>
                <li><Link href="/library" className="hover:text-zinc-900 dark:hover:text-zinc-100">{t.nav.library}</Link></li>
                <li><Link href="/courses" className="hover:text-zinc-900 dark:hover:text-zinc-100">Courses</Link></li>
                <li><Link href="/research" className="hover:text-zinc-900 dark:hover:text-zinc-100">Research &amp; Stats</Link></li>
                <li><Link href="/community" className="hover:text-zinc-900 dark:hover:text-zinc-100">Community</Link></li>
              </ul>
            </div>

            {/* LEGAL column */}
            <div>
              <h3 className="text-[11px] font-semibold uppercase tracking-[0.14em] text-zinc-500 dark:text-slate-400">
                Company
              </h3>
              <ul className="mt-4 space-y-2 text-sm">
                <li><Link href="/about" className="hover:text-zinc-900 dark:hover:text-zinc-100">{t.footer.about}</Link></li>
                <li><Link href="/contact" className="hover:text-zinc-900 dark:hover:text-zinc-100">{t.footer.contact}</Link></li>
                <li><Link href="/privacy" className="hover:text-zinc-900 dark:hover:text-zinc-100">{t.footer.privacy}</Link></li>
                <li><Link href="/terms" className="hover:text-zinc-900 dark:hover:text-zinc-100">{t.footer.terms}</Link></li>
                <li><Link href="/refund" className="hover:text-zinc-900 dark:hover:text-zinc-100">Refund policy</Link></li>
                <li><Link href="/disclaimer" className="hover:text-zinc-900 dark:hover:text-zinc-100">{t.footer.medicalDisclaimer}</Link></li>
              </ul>
            </div>
          </div>

          <div className="border-t border-zinc-200 dark:border-slate-800/60">
            <div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-2 px-4 py-5 text-[11px] text-zinc-500 dark:text-slate-500 sm:px-6 sm:flex-row">
              <p>© {new Date().getFullYear()} MedExam Hub. All rights reserved.</p>
              <p className="italic">Built for medical students, residents and doctors.</p>
            </div>
          </div>
        </footer>
        <WhatsAppButton />
        <ServiceWorkerRegister />
      </body>
    </html>
  );
}
