export const metadata = { title: "Medical Disclaimer — MedExam Hub" };

export default function DisclaimerPage() {
  return (
    <article className="mx-auto max-w-3xl px-6 py-12 prose prose-zinc dark:prose-invert">
      <h1>Medical Disclaimer</h1>
      <p className="text-sm text-zinc-500">Last updated: 2026-05-03</p>

      <div className="rounded-md border border-amber-200 bg-amber-50 p-4 text-amber-900 dark:border-amber-900 dark:bg-amber-950 dark:text-amber-200">
        <strong>For educational use only.</strong> MedExam Hub is a study and exam-preparation
        platform. It does not provide medical advice, diagnosis, or treatment recommendations for
        real patients.
      </div>

      <h2>About AI-generated content</h2>
      <p>
        Questions and explanations on MedExam Hub are generated by artificial intelligence (AI)
        large-language models. While we structure prompts to align with current major clinical
        guidelines (USMLE, MRCS, MRCP, NICE, AHA, ESC, etc.), AI-generated medical content can:
      </p>
      <ul>
        <li>Contain factual errors, hallucinations, or outdated information.</li>
        <li>Reflect biases present in its training data.</li>
        <li>Omit context relevant to your specific clinical setting.</li>
      </ul>

      <h2>What you must do</h2>
      <ul>
        <li>Use this platform <strong>only for studying and exam preparation</strong>.</li>
        <li>
          Always verify clinical information against authoritative sources before applying it:
          official guidelines (NICE, AHA, ESC, your local ministry of health), peer-reviewed
          journals, current textbooks, and your institution&apos;s protocols.
        </li>
        <li>
          Defer to qualified colleagues, supervisors, and your professional medical training when
          making patient-care decisions.
        </li>
        <li>Report errors you encounter so we can improve prompt quality.</li>
      </ul>

      <h2>What this platform is NOT</h2>
      <ul>
        <li>A substitute for medical school, residency, or supervised clinical training.</li>
        <li>A diagnostic tool for real patients.</li>
        <li>A source of definitive medical truth.</li>
        <li>Endorsed by, or affiliated with, USMLE, MRCS, MRCP, the Egyptian Medical Syndicate, or any examination body. Exam names are referenced for descriptive purposes only.</li>
      </ul>

      <h2>Liability</h2>
      <p>
        MedExam Hub and its operators accept no liability for any clinical decision, patient harm,
        examination failure, or other consequence resulting from use of AI-generated content on
        this platform. Use of the service constitutes acceptance of this risk.
      </p>
    </article>
  );
}
